name: Build and Push Crawlee Images on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    name: Build and Push Crawlee Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set DEV image tag
        id: set-tag
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/}
          DEV_IMAGE_TAG="dev-${GIT_TAG}"
          echo "DEV_IMAGE_TAG=${DEV_IMAGE_TAG}" >> $GITHUB_ENV
          echo "dev_image_tag=${DEV_IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push DEV Crawlee image to Amazon ECR
        id: build-dev-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          set -euo pipefail
          echo "Building DEV Crawlee image with tag: $DEV_IMAGE_TAG"

          docker build \
            --build-arg S3_BUCKET_NAME=${{ vars.S3_BUCKET_NAME }} \
            --build-arg AWS_REGION=${{ vars.CRAWLEE_AWS_REGION }} \
            --build-arg AWS_KEY=${{ secrets.CRAWLEE_AWS_KEY }} \
            --build-arg AWS_SECRET=${{ secrets.CRAWLEE_AWS_SECRET }} \
            --build-arg MINIO_ENDPOINT=${{ vars.MINIO_ENDPOINT }} \
            --build-arg INGEST_URL=${{ vars.INGEST_URL }} \
            --build-arg NO_CRAWL=${{ vars.NO_CRAWL }} \
            --build-arg PORT=${{ vars.CRAWLEE_PORT }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$DEV_IMAGE_TAG .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DEV_IMAGE_TAG

      - name: Output DEV image tag
        run: |
          echo "DEV Crawlee image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.DEV_IMAGE_TAG }}"


  build-and-push-prod:
    name: Build and Push PROD Crawlee Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set image tag
        id: set-tag
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/}
          IMAGE_TAG="${GIT_TAG}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
      - name: Login to docker registry
        uses: docker/login-action@v4
        with:
          registry: docker-registry.osc.edu
          username: ${{ secrets.OSC_REGISTRY_ROBOT_OSC_USERNAME }}
          password: ${{ secrets.OSC_REGISTRY_ROBOT_OSC_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: docker-registry.osc.edu/osc/crawlee:${{ env.IMAGE_TAG }}
